// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_complete_mp_price_woodland");
	self setViewmodel("viewhands_black_kit");
	self.voice = "british";
}

precache()
{
	precacheModel("body_complete_mp_price_woodland");
	precacheModel("viewhands_black_kit");
}
