// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_complete_mp_velinda_woodland");
	self setViewmodel("viewmodel_base_viewhands");
	self.voice = "american";
}

precache()
{
	precacheModel("body_complete_mp_velinda_woodland");
	precacheModel("viewmodel_base_viewhands");
}
