// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_complete_mp_zakhaev");
	self setViewmodel("viewhands_op_force");
}

precache()
{
	precacheModel("body_complete_mp_zakhaev");
	precacheModel("viewhands_op_force");
}
